site_name: "Project: Doodle Guidebook"
use_directory_urls: false
nav:
  - Home: index.md
  - About: about.md
  - "Custom Doodads": custom-doodads/index.md
markdown_extensions:
  - toc:
      permalink: "#"
